### ISSUE TITLE
Website -> 404

### ISSUE THREAD

**Issue by arguiot** [atomiclabs/cryptocurrency-icons-website#1]
The URL http://cryptoicons.co is pointing toward a non-existing page.

**Comment by sindresorhus** [comment]
Yes, the GitHub interface is not letting me update the location.

You can access the website at https://atomiclabs.github.io/cryptocurrency-icons-website/ in the meantime while I contact GitHub about it.

**Comment by sindresorhus** [comment]
Alright, it worked now: http://cryptoicons.co
