### ISSUE TITLE
[Request] Icons without round

### ISSUE THREAD

**Issue by mesqueeb** [atomiclabs/cryptocurrency-icons-website#3]
Great website!!
Thank you so much! Are these royalty free?

Will you add a regular, not in a round shape icons as well?

Best regards,

**Comment by sindresorhus** [comment]
> Are these royalty free?

Yes: https://github.com/atomiclabs/cryptocurrency-icons/blob/master/LICENSE.md

> Will you add a regular, not in a round shape icons as well?

We have no plans to do that.
